from pydantic import BaseModel,Field, field_validator,EmailStr
from typing import Dict, Any
from datetime import datetime
from typing import Optional, List

# === USER SCHEMAS ===
class UserBase(BaseModel):
    email: EmailStr
    username: str
    full_name: Optional[str] = None

class UserCreate(UserBase):
    full_name:str
    username:str
    email:str
    password: str
  
class UserResponse(UserBase):
    id: int
    is_active: bool
    is_verified: bool
    created_at: datetime
    mental_age: Optional[int] = None
    assessment_date: Optional[datetime] = None

    class Config:
        from_attributes = True

class UserLogin(BaseModel):
    email: EmailStr
    password: str

class Token(BaseModel):
    access_token: str
    token_type: str

class TokenData(BaseModel):
    email: Optional[str] = None

class UserDetails(UserBase):
    id: int
    is_active: bool
    is_verified: bool
    created_at: datetime
    mental_age: Optional[int] = None
    intellect_level: Optional[str] = None
    assesment_progress: Optional[str] = None
    assessment_date: Optional[datetime] = None

    class Config:
        from_attributes = True

# === CHATBOT SCHEMAS ===

class ChatMessage(BaseModel):
    message: str = Field(..., min_length=1, max_length=1000, description="User message to the chatbot")
    timestamp: Optional[datetime] = Field(default_factory=datetime.utcnow)

class ChatResponse(BaseModel):
    response: str
    stage: str
    mental_age: Optional[int] = None
    intellect_level: Optional[str] = None
    progress: Optional[str] = None
    assessment_complete: Optional[bool] = False
    conversation_state: Optional[Dict[str, Any]] = "welcome"
    timestamp: datetime = Field(default_factory=datetime.utcnow)

class InitializeChatbotResponse(BaseModel):
    session_id: str
    initial_response: ChatResponse
    status: str
    user_id: int

class AssessmentReport(BaseModel):
    mental_age: int
    intellect_level: str
    detailed_report: str
    assessment_data: List[Dict[str, Any]]
    generated_at: datetime = Field(default_factory=datetime.utcnow)

class LearningRecommendation(BaseModel):
    topic: Optional[str] = None
    subject_filter: Optional[str] = None

class ChatbotStatus(BaseModel):
    user_id: int
    current_stage: str
    mental_age: Optional[int]
    intellect_level: Optional[str]
    assessment_progress: Optional[str]
    last_interaction: Optional[datetime]

class ErrorResponse(BaseModel):
    error: str
    message: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# --- QUIZ MODELS ---

class QuizQuestion(BaseModel):
    question_id: Optional[int] = None  # optional for creation, auto-generated by DB
    question_text: str
    options: List[str]
    correct_option_index: Optional[int] = None  # Keep hidden from frontend if needed

class Quiz(BaseModel):
    quiz_id: Optional[int] = None
    title: str
    description: Optional[str] = None
    questions: List[QuizQuestion]

class QuizAnswer(BaseModel):
    question_id: int
    selected_option_index: int

class QuizSubmission(BaseModel):
    user_id: int
    quiz_id: int
    answers: List[QuizAnswer]

class QuizResult(BaseModel):
    user_id: int
    quiz_id: int
    score: int
    total_questions: int
    submitted_at: datetime


# format info for dashboard
# const mockData = {
#         username: "Alex",
#         user: {
#           mental_age: 12,
#           intellect_level: "Advanced",
#           assessment_progress: "75%"
#         },
#         quiz_stats: {
#           completed_quizzes: 15,
#           average_score: 87,
#           recent_scores: [92, 88, 95, 85, 90]
#         },
#         learning_streak: 7,
#         homework_stats: {
#           completed_homework: 12,
#           pending_homework: 3,
#           submission_rate: 80
#         },
#         badges_earned: ["Quick Learner", "Perfect Score", "Week Warrior", "Math Master"],
#         recent_activities: [
#           {
#             type: "quiz",
#             description: "Completed Science Quiz",
#             timestamp: "2 hours ago",
#             points: 50
#           },
#           {
#             type: "homework",
#             description: "Submitted Math Homework",
#             timestamp: "5 hours ago",
#             points: 30
#           },
#           {
#             type: "badge",
#             description: "Earned 'Week Warrior' Badge",
#             timestamp: "1 day ago",
#             points: 100
#           },
#           {
#             type: "assessment",
#             description: "Completed Assessment Module",
#             timestamp: "2 days ago",
#             points: 75
#           }
#         ]
#       };

class RecentActivity(BaseModel):
    type: str
    description: str
    timestamp: str
    points: int


class QuizStats(BaseModel):
    completed_quizzes: int
    average_score: float
    recent_scores: List[int]


class HomeworkStats(BaseModel):
    completed_homework: int
    pending_homework: int
    submission_rate: float


class UserDashboardData(BaseModel):
    mental_age: Optional[int] = None
    intellect_level: Optional[str] = None
    assessment_progress: Optional[str] = None



class DashboardInfo(BaseModel):
    username: str
    user: UserDashboardData
    quiz_stats: QuizStats
    learning_streak: int
    homework_stats: HomeworkStats
    badges_earned: List[str]
    recent_activities: List[RecentActivity]

    class Config:
        from_attributes = True


